server:
  port: 8082

spring:
  application:
    name: jag-usuario-service

  datasource:
    url: jdbc:h2:mem:jag-usuario
    driver-class-name: org.h2.Driver
    username: jag
    password: root

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
