server:
  port: 8083

spring:
  application:
    name: jag-prestamo-service

  datasource:
    url: jdbc:mysql://localhost:3306/jag_prestamo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Cambia este puerto si tu jag-registry-service está en otro
  instance:
    hostname: localhost
