server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # O el puerto que usaste en jag-registry-service
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Ojo: debe ser `enabled`, no `enable`
      routes:
        - id: jag-libro-service
          uri: lb://jag-libro-service
          predicates:
            - Path=/libros/**
        - id: jag-usuario-service
          uri: lb://jag-usuario-service
          predicates:
            - Path=/usuarios/**
        - id: jag-prestamo-service
          uri: lb://jag-prestamo-service
          predicates:
            - Path=/prestamos/**
